--- 

- hosts: master 
  gather_facts: true  
  become: yes  
  become_method: sudo  
        
  tasks:
    - name: Install common packages on Ansible controller
      yum:
        state: present        
        name:
          - elinks
          - tree
          - git
