---

- hosts: all
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:
  - name: Copy microsoft repo file
    copy:
      src: files/powershell/microsoft.repo
      dest: /etc/yum.repos.d/microsoft.repo
      owner: root
      group: root
      mode: '0644'
  - name: Remove powershell-preview package
    yum:
      name: powershell-preview
      state: absent
  - name: Install powershell 7 package
    yum:
      name: powershell
      state: latest
  - name: Rmove Powershell preview path from $path
    file:
      dest: /etc/profile.d/ansible-path.sh
      state: absent
