---

- hosts: all
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:
  - name: Copy microsoft repo file
    copy:
      src: files/powershell/microsoft.repo
      dest: /etc/yum.repos.d/microsoft.repo
      owner: root
      group: root
      mode: '0644'
  - name: Install powershell package
    yum:
      name: powershell
      state: latest

