--- 

- hosts: all
  gather_facts: true  
  become: yes  
  become_method: sudo  
        
  tasks:    
    - debug:
            msg: "I am connecting to {{ ansible_nodename }} which is        
            running {{ ansible_distribution }}        
            {{ ansible_distribution_version }}"
    - yum:        
        name: "*"        
        state: "latest"
      when: ansible_facts['os_family'] == "RedHat"
    - apt:
        name: "*"
        state: "latest"
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
